name: Frontend CI/CD

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy via SCP
        env:
          PRIVATE_KEY: ${{ secrets.YEDOC }}
          HOST: ${{ secrets.FRONTEND_HOST }}
        run: |
          echo "$PRIVATE_KEY" > key.pem
          chmod 600 key.pem

          scp -i key.pem -o StrictHostKeyChecking=no -r dist ec2-user@$HOST:/home/ec2-user/frontend-dist

          # SSH 접속 후 sudo 권한으로 nginx 경로에 복사
          ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@$HOST << 'EOF'
            sudo rm -rf /usr/share/nginx/html/*
            sudo cp -r /home/ec2-user/frontend-dist/* /usr/share/nginx/html/
          EOF
